{{- if .Values.initJob.enabled }}
{{- if .Values.initJob.importFilterLua.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-importfilterlua" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  importFilter.lua: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.initJob.importFilterLua.configuration "context" $ ) | nindent 4 }}
{{- end -}}
{{- end -}}
